<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Reservations\Commands\CreateReservation\" />
    <Folder Include="Reservations\Commands\CancelReservation\" />
    <Folder Include="Reservations\EventHandlers\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ceiba.LiveEvent.Reservations.Application</RootNamespace>
    <AssemblyName>Ceiba.LiveEvent.Reservations.Application</AssemblyName>
  </PropertyGroup>

</Project>
